name: Docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # версия OS
#    env:
#      LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
#      NAME: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Docker build  # Строим контейнер
        run: |
          docker build . -t automation-tests
      - name: Docker run  # Прогоняем контейнер
        run: |
          docker run -t automation-tests