name: Code checks  # имя

on:  # на какие события срабатывает pipeline
  push: # срабатывает на push...
    branches: [ master ]  # ... в бранч master
  pull_request: # срабатывает на pull request...
    branches: [ master ]  # ... в бранч master

jobs:  # что будет выполнено, когда произойдет какое-либо событие, указанное выше
  build:
    runs-on: ubuntu-latest  # версия OS
    steps:
      - uses: actions/checkout@v2  # создается образ репозитория, в котором будут выполнены дальнейшие шаги
      - name: Docker login
        uses: docker/login-action@v1

        #with:
        env:
          #DOCKER_USER: ${{ secrets.DOCKER_USER }}
          username: ${{ secrets.DOCKER_USER }}
          #DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Docker build  # Строим контейнер
        run: |
          docker build . -t automation-tests
      - name: Docker run  # Прогоняем контейнер
        run: |
          docker run automation-tests