name: Docker image build and push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:  #
      - name: Checkout    # Чекаем репозиторий
        uses: actions/checkout@v3

      - name: Set up Docker Buildx  # Настраиваем билдер
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub  # Логинимся в hub.docker.com
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push  # Строим и пушим образ в hub.docker.com
        uses: docker/build-push-action@v3
        with:
          context: .  # Если Dockerfile лежит не в корне, то точку заменяем на ./имя_папки
          push: true
          tags: |  # username/имя репозитория на hub.docker.com: тег
            ${{ secrets.DOCKERHUB_USERNAME }}/automation-tests:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/automation-tests:latest