name: Docker build and push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # версия OS

    steps:
#      - name: Docker build  # Строим контейнер
#        run: |
#          docker build . -t automation-tests
#      - name: Docker run  # Прогоняем контейнер
#        run: |
#          docker run -t automation-tests


      - name: Build and push image to the Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
