name: Docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # версия OS
#    env:
#      LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
#      NAME: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:  #
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - uses: actions/checkout@v2
      - name: Docker build  # Строим контейнер
        run: |
          docker build . -t automation-tests
#      - name: Docker run  # Прогоняем контейнер
#        run: |
#          docker run -t automation-tests

