name: Docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest  # версия OS
#    env:
#      LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
#      NAME: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:  #
#      - name: Checkout
      - uses: actions/checkout@v2

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker build  # Строим контейнер
        run: |
          docker build . -t automation-tests

      - name: Docker push  # Пушим контейнер
        run: |
          docker push automation-tests

#      - name: Docker run  # Прогоняем контейнер
#        run: |
#          docker run -t automation-tests

